using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using ShipNex.Application.Interfaces;

namespace ShipNex.Infrastructure.Services;

/// <summary>
/// Supabase Storage implementation for secure shipment document storage.
///
/// Security model:
/// - The bucket is PRIVATE. Objects can never be read without either the
///   service key (server-side only) or a signed URL minted by this service.
/// - The service role key stays in server configuration and is never returned
///   to clients.
/// - Object paths are always generated server-side (date + GUID + validated
///   extension); client file names are metadata only, so path traversal via
///   the upload name is impossible.
/// - Temporary access uses Supabase signed URLs with a bounded expiry.
/// </summary>
public class SupabaseFileStorageService : IFileStorageService
{
    private readonly HttpClient _http;
    private readonly ILogger<SupabaseFileStorageService> _logger;
    private readonly string _baseUrl;      // e.g. https://xyz.supabase.co
    private readonly string _serviceKey;   // service_role key — SERVER ONLY
    private readonly string _bucket;       // private bucket name
    private readonly string _allowedExtensions = ".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.gif,.webp,.txt,.csv";
    private readonly long _maxFileSize = 10 * 1024 * 1024; // 10 MB

    public SupabaseFileStorageService(HttpClient http, IConfiguration configuration, ILogger<SupabaseFileStorageService> logger)
    {
        _http = http;
        _logger = logger;

        _baseUrl = (configuration["FileStorage:SupabaseUrl"] ?? string.Empty).TrimEnd('/');
        _serviceKey = configuration["FileStorage:SupabaseServiceKey"] ?? string.Empty;
        _bucket = configuration["FileStorage:SupabaseBucket"] ?? "shipment-documents";

        if (string.IsNullOrWhiteSpace(_baseUrl) || string.IsNullOrWhiteSpace(_serviceKey))
        {
            throw new InvalidOperationException(
                "Supabase storage is selected but FileStorage:SupabaseUrl / FileStorage:SupabaseServiceKey are not configured. " +
                "Set them via environment variables FileStorage__SupabaseUrl and FileStorage__SupabaseServiceKey.");
        }

        _http.BaseAddress ??= new Uri(_baseUrl);
        _http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _serviceKey);
        _http.DefaultRequestHeaders.Add("apikey", _serviceKey);
    }

    /// <summary>Builds a server-controlled object path. Never trust client input here.</summary>
    private static string BuildObjectPath(string fileId, string fileName)
    {
        // fileId is generated by UploadAsync ("yyyyMMdd_hexguid"); the extension
        // is re-derived and validated so nothing client-supplied reaches the path.
        var extension = Path.GetExtension(fileName)?.ToLowerInvariant() ?? string.Empty;
        if (extension.Length is < 2 or > 6 || extension.Any(c => !char.IsAsciiLetterOrDigit(c) && c != '.'))
            throw new ArgumentException("Invalid file extension.", nameof(fileName));
        return $"{DateTime.UtcNow:yyyy/MM}/{fileId}{extension}";
    }

    public async Task<string> UploadAsync(Stream fileStream, string fileName, string contentType)
    {
        ValidateFile(fileName, contentType);

        var fileId = $"{DateTime.UtcNow:yyyyMMdd}_{Guid.NewGuid():N}";
        var objectPath = BuildObjectPath(fileId, fileName);

        using var content = new StreamContent(fileStream);
        content.Headers.ContentType = new MediaTypeHeaderValue(contentType);

        using var response = await _http.PostAsync($"/storage/v1/object/{_bucket}/{objectPath}", content);
        if (!response.IsSuccessStatusCode)
        {
            var body = await response.Content.ReadAsStringAsync();
            _logger.LogError("Supabase upload failed ({Status}): {Body}", response.StatusCode, body);
            throw new InvalidOperationException($"Supabase Storage upload failed ({(int)response.StatusCode}).");
        }

        _logger.LogInformation("File uploaded to Supabase bucket {Bucket}: {Path}", _bucket, objectPath);
        return fileId;
    }

    public async Task<string> UploadAsync(byte[] fileData, string fileName, string contentType)
    {
        ValidateFile(fileName, contentType);

        if (fileData == null || fileData.Length == 0)
            throw new ArgumentException("File data must not be empty.", nameof(fileData));
        if (fileData.Length > _maxFileSize)
            throw new ArgumentException($"File exceeds the maximum allowed size of {_maxFileSize} bytes.", nameof(fileData));

        using var stream = new MemoryStream(fileData);
        return await UploadAsync(stream, fileName, contentType);
    }

    public async Task<Stream> DownloadAsync(string fileId)
    {
        var objectPath = await ResolveObjectPathAsync(fileId);
        using var request = new HttpRequestMessage(HttpMethod.Get, $"/storage/v1/object/{_bucket}/{objectPath}");
        using var response = await _http.SendAsync(request);
        if (!response.IsSuccessStatusCode)
            throw new FileNotFoundException($"File with ID '{fileId}' not found in storage.");

        var memoryStream = new MemoryStream();
        await response.Content.CopyToAsync(memoryStream);
        memoryStream.Position = 0;
        return memoryStream;
    }

    public async Task<byte[]> DownloadBytesAsync(string fileId)
    {
        await using var stream = await DownloadAsync(fileId);
        using var memory = new MemoryStream();
        await stream.CopyToAsync(memory);
        return memory.ToArray();
    }

    public async Task<bool> DeleteAsync(string fileId)
    {
        var objectPath = await ResolveObjectPathAsync(fileId);
        using var request = new HttpRequestMessage(HttpMethod.Delete, $"/storage/v1/object/{_bucket}/{objectPath}");
        using var response = await _http.SendAsync(request);
        if (response.IsSuccessStatusCode || response.StatusCode == System.Net.HttpStatusCode.NotFound)
        {
            _logger.LogInformation("File deleted from Supabase bucket {Bucket}: {Path}", _bucket, objectPath);
            return true;
        }
        _logger.LogWarning("Supabase delete failed for {Path} ({Status})", objectPath, response.StatusCode);
        return false;
    }

    public async Task<bool> ExistsAsync(string fileId)
    {
        try
        {
            await ResolveObjectPathAsync(fileId);
            return true;
        }
        catch (FileNotFoundException)
        {
            return false;
        }
    }

    public string GetFileUrl(string fileId) => $"/api/documents/download/{fileId}";

    /// <summary>
    /// Mints a short-lived signed URL for a private object. The service key is
    /// never embedded in the returned URL — the signed token alone grants
    /// time-boxed read access.
    /// </summary>
    public async Task<string> CreateTemporaryAccessUrlAsync(string fileId, int expiresInSeconds)
    {
        ValidateFileId(fileId);
        var objectPath = await ResolveObjectPathAsync(fileId);

        // Supabase signed URL: POST /storage/v1/object/sign/{bucket}/{path} { expiresIn }
        using var response = await _http.PostAsJsonAsync(
            $"/storage/v1/object/sign/{_bucket}/{objectPath}",
            new { expiresIn = expiresInSeconds });
        if (!response.IsSuccessStatusCode)
        {
            var body = await response.Content.ReadAsStringAsync();
            _logger.LogError("Supabase sign failed ({Status}): {Body}", response.StatusCode, body);
            throw new InvalidOperationException($"Could not create a temporary access URL ({(int)response.StatusCode}).");
        }

        using var doc = JsonDocument.Parse(await response.Content.ReadAsStringAsync());
        var signed = doc.RootElement.TryGetProperty("signedURL", out var url) ? url.GetString() : null;
        if (string.IsNullOrWhiteSpace(signed))
            throw new InvalidOperationException("Supabase did not return a signed URL.");

        return $"{_baseUrl}/storage/v1{signed}";
    }

    /// <summary>
    /// Finds the object path for a fileId by listing the month prefixes used at
    /// upload time (paths are server-generated "yyyy/MM/fileId.ext").
    /// </summary>
    private async Task<string> ResolveObjectPathAsync(string fileId)
    {
        ValidateFileId(fileId);

        // Check the most recent months first; fall back to a broader prefix search.
        var now = DateTime.UtcNow;
        for (var monthsBack = 0; monthsBack < 24; monthsBack++)
        {
            var prefix = now.AddMonths(-monthsBack).ToString("yyyy/MM");
            var listUrl = $"/storage/v1/object/list/{_bucket}?prefix={Uri.EscapeDataString(prefix + "/")}&limit=100";
            using var response = await _http.GetAsync(listUrl);
            if (!response.IsSuccessStatusCode) continue;

            await using var stream = await response.Content.ReadAsStreamAsync();
            using var doc = await JsonDocument.ParseAsync(stream);
            foreach (var item in doc.RootElement.EnumerateArray())
            {
                if (!item.TryGetProperty("name", out var nameEl)) continue;
                var name = nameEl.GetString();
                if (string.IsNullOrEmpty(name)) continue;
                var fileName = name[(name.LastIndexOf('/') + 1)..];
                if (fileName.StartsWith(fileId, StringComparison.Ordinal))
                    return name;
            }
        }

        throw new FileNotFoundException($"File with ID '{fileId}' not found in storage.");
    }

    private void ValidateFile(string fileName, string contentType)
    {
        if (string.IsNullOrWhiteSpace(fileName))
            throw new ArgumentException("File name is required.", nameof(fileName));

        var extension = Path.GetExtension(fileName).ToLowerInvariant();
        if (string.IsNullOrEmpty(extension))
            throw new ArgumentException("File must have an extension.", nameof(fileName));

        var blocked = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            { ".exe", ".dll", ".bat", ".cmd", ".com", ".scr", ".msi", ".ps1", ".sh", ".js", ".vbs", ".jar" };
        if (blocked.Contains(extension))
            throw new ArgumentException($"Executable and script files ('{extension}') are not allowed.", nameof(fileName));

        if (!_allowedExtensions.Split(',').Contains(extension))
            throw new ArgumentException($"File type '{extension}' is not allowed. Allowed types: {_allowedExtensions}", nameof(fileName));

        if (string.IsNullOrWhiteSpace(contentType))
            throw new ArgumentException("Content type is required.", nameof(contentType));
    }

    private static void ValidateFileId(string? fileId)
    {
        if (string.IsNullOrWhiteSpace(fileId))
            throw new ArgumentException("File id must not be empty.", nameof(fileId));
        if (fileId.Length > 64)
            throw new ArgumentException("File id is too long.", nameof(fileId));
        foreach (var c in fileId)
        {
            if (!char.IsAsciiLetterOrDigit(c) && c != '_')
                throw new ArgumentException("File id contains invalid characters.", nameof(fileId));
        }
    }
}
