$path = 'C:\Users\Falone Mo\Desktop\shipnex-website\backend\tests\ShipNex.Application.Tests\ShipmentServiceTests.cs'
$lines = @()
$lines += 'using System;'
$lines += 'using System.Linq;'
$lines += 'using System.Threading.Tasks;'
$lines += 'using Microsoft.EntityFrameworkCore;'
$lines += 'using Moq;'
$lines += 'using Xunit;'
$lines += 'using ShipNex.Application.DTOs;'
$lines += 'using ShipNex.Application.Interfaces;'
$lines += 'using ShipNex.Domain.Entities;'
$lines += 'using ShipNex.Domain.Enums;'
$lines += 'using ShipNex.Domain.ValueObjects;'
$lines += 'using ShipNex.Infrastructure.Data;'
$lines += 'using ShipNex.Infrastructure.Services;'
$lines += ''
$lines += 'namespace ShipNex.Application.Tests;'
$lines += ''
$lines += 'public class ShipmentServiceTests : IDisposable'
$lines += '{'
$lines += '    private readonly ShipNexDbContext _context;'
$lines += '    private readonly Mock<ITrackingNumberGenerator> _trackingMock;'
$lines += '    private readonly Mock<IAuditService> _auditMock;'
$lines += '    private readonly Mock<INotificationService> _notificationMock;'
$lines += '    private readonly ShipmentService _service;'
$lines += ''
$lines += '    public ShipmentServiceTests()'
$lines += '    {'
$lines += '        var options = new DbContextOptionsBuilder<ShipNexDbContext>()'
$lines += '            .UseInMemoryDatabase(databaseName: $"ShipmentTests_{Guid.NewGuid()}")'
$lines += '            .Options;'
$lines += ''
$lines += '        _context = new ShipNexDbContext(options);'
$lines += '        _trackingMock = new Mock<ITrackingNumberGenerator>();'
$lines += '        _auditMock = new Mock<IAuditService>();'
$lines += '        _notificationMock = new Mock<INotificationService>();'
$lines += ''
$lines += '        _service = new ShipmentService('
$lines += '            _context,'
$lines += '            _trackingMock.Object,'
$lines += '            _auditMock.Object,'
$lines += '            _notificationMock.Object);'
$lines += '    }'
$lines += ''
$lines += '    public void Dispose()'
$lines += '    {'
$lines += '        _context.Database.EnsureDeleted();'
$lines += '        _context.Dispose();'
$lines += '    }'
$lines += '}'
Set-Content -Path $path -Value ($lines -join [Environment]::NewLine)
